FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
ADD package.json /usr/src/app/
ADD server.js /usr/src/app/

VOLUME /usr/src/app/

RUN npm install

EXPOSE 80
CMD [ "npm", "start" ]